server {
    listen 8080;
    server_name _;

    location = /.well-known/matrix/client {
        default_type application/json;
        add_header Access-Control-Allow-Origin * always;
        root /usr/share/nginx/html;
    }

    location = /.well-known/matrix/server {
        default_type application/json;
        root /usr/share/nginx/html;
    }

    location / {
        return 404;
    }
}
